"""
Django settings for hospital_management project.

Generated by 'django-admin startproject' using Django 3.2.8.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-49k2lqwahcnmml2_#6k(9+q%aov^kv2c4y4-x!cu!r=sr*+9s-')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG to False in production by setting the environment variable in Vercel
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Add Vercel domain and localhost to Allowed Hosts
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.vercel.app', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'patient',
    'doctor',
    'staff',
    'widget_tweaks',
    'hospital_management',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must be right after SecurityMiddleware to serve static files on Vercel
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hospital_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hospital_management.wsgi.application'


# Database
# Safely import credentials for local development without crashing Vercel builds
try:
    from .credentials import database
    DATABASES = {
        'default': database
    }
except ImportError:
    # Fallback database configuration when credentials.py is missing (like on Vercel)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = '/static/'

# Detect if running on Vercel
IS_VERCEL = os.environ.get('VERCEL') == '1'

# For Vercel: Collect static files to staticfiles_build directory during build
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build')

# Include all static directories from all apps
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'hospital_management', 'static'),
    os.path.join(BASE_DIR, 'doctor', 'static'),
    os.path.join(BASE_DIR, 'patient', 'static'),
    os.path.join(BASE_DIR, 'staff', 'static'),
]

# WhiteNoise configuration for production static file serving
# Use CompressedStaticFilesStorage which doesn't require manifest.json
if IS_VERCEL:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Critical: Force WhiteNoise to look in source directories on Vercel
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL after correct login
LOGIN_REDIRECT_URL = '/after-login'
LOGOUT_REDIRECT_URL = '/'