# Generated by Django 3.2.8 on 2021-10-21 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('contact_no', models.CharField(max_length=10)),
                ('symptoms', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6)),
                ('department', models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Immunologists', 'Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='General Physician', max_length=30)),
                ('assigned_doctor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DischargeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('room_charge', models.PositiveIntegerField()),
                ('medicine_charge', models.PositiveIntegerField()),
                ('doctor_charge', models.PositiveIntegerField()),
                ('other_charge', models.PositiveIntegerField()),
                ('total_charge', models.PositiveIntegerField()),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=400)),
                ('status', models.BooleanField(default=False)),
                ('assigned_doctor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
        ),
    ]
