# Generated by Django 3.2.8 on 2021-10-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20211023_1502'),
        ('patient', '0003_patient_status'),
    ]

    operations = [
    ]
