# Generated by Django 3.2.8 on 2021-10-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_id'),
        ('patient', '0005_auto_20211024_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ManyToManyField(null=True, to='doctor.Doctor'),
        ),
    ]
