# Generated by Django 3.2.8 on 2021-10-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20211027_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargedetails',
            name='doctor_name',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AddField(
            model_name='dischargedetails',
            name='patient_name',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='dischargedetails',
            name='doctor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dischargedetails',
            name='patient',
            field=models.PositiveIntegerField(),
        ),
    ]
