# Generated by Django 3.2.8 on 2021-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveIntegerField(null=True)),
                ('patient_name', models.CharField(max_length=40, null=True)),
                ('doctor_id', models.PositiveIntegerField(null=True)),
                ('doctor_name', models.CharField(max_length=40, null=True)),
                ('appointment_date', models.DateField(auto_now=True)),
                ('prescription', models.TextField(max_length=500)),
                ('medicines', models.TextField(max_length=500)),
            ],
        ),
    ]
